check fix sonarqube test_ui

diff --git a/.github/workflows/sonarcloud.yaml b/.github/workflows/sonarcloud.yaml
--- a/.github/workflows/sonarcloud.yaml
+++ b/.github/workflows/sonarcloud.yaml
@@ -33,43 +33,6 @@ jobs:
         run: npm ci
         working-directory: front-end
 
-      
-      # START both FE and BE
-      - name: Start Backend
-        run: nohup npm run start:test >/dev/null 2>&1 &
-        working-directory: back-end
-        env:
-          NODE_ENV: test
-
-      - name: Wait for Backend
-        run: |
-          for i in {1..30}; do
-            if curl -s http://localhost:3000/is_on > /dev/null; then
-              echo "Backend UP";
-              exit 0;
-            fi
-            echo "Waiting for backend...";
-            sleep 2;
-          done
-          echo "Backend FAILED to start";
-          exit 1
-
-      - name: Start Frontend
-        run: nohup npm run dev >/dev/null 2>&1 &
-        working-directory: front-end
-
-      - name: Wait for Frontend
-        run: |
-          for i in {1..30}; do
-            if curl -s http://localhost:5173 > /dev/null; then
-              echo "Frontend UP";
-              exit 0;
-            fi
-            echo "Waiting for frontend...";
-            sleep 2;
-          done
-          echo "Frontend FAILED to start";
-          exit 1
 
       # 4. Run Unit Tests
       # Questo crea il report in coverage/unit/lcov.info
@@ -102,7 +65,44 @@ jobs:
           NODE_ENV: 'test'
           DB_PATH: ''
 
-        
+      # START both FE and BE
+      - name: Start Backend
+        run: nohup npm run start:test >/dev/null 2>&1 &
+        working-directory: back-end
+        env:
+          NODE_ENV: test
+
+      - name: Wait for Backend
+        run: |
+          for i in {1..30}; do
+            if curl -s http://localhost:3001/is_on > /dev/null; then
+              echo "Backend UP";
+              exit 0;
+            fi
+            echo "Waiting for backend...";
+            sleep 2;
+          done
+          echo "Backend FAILED to start";
+          exit 1
+
+      - name: Start Frontend
+        run: nohup npm run dev >/dev/null 2>&1 &
+        working-directory: front-end
+
+      - name: Wait for Frontend
+        run: |
+          for i in {1..30}; do
+            if curl -s http://localhost:5173 > /dev/null; then
+              echo "Frontend UP";
+              exit 0;
+            fi
+            echo "Waiting for frontend...";
+            sleep 2;
+          done
+          echo "Frontend FAILED to start";
+          exit 1
+
+          
       # Install Chrome
       - name: Install Google Chrome
         uses: browser-actions/setup-chrome@v1
